
export const allEvents = [
    // 2024
    { date: "Aug 15, 2024", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day", longWeekend: true },
    { date: "Aug 19, 2024", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan", longWeekend: true },
    { date: "Aug 26, 2024", name: "Janmashtami", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Sep 07, 2024", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Sep 15, 2024", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam", longWeekend: true },
    { date: "Oct 02, 2024", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 03 - Oct 11, 2024", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri", longWeekend: true },
    { date: "Oct 09 - Oct 13, 2024", name: "Durga Puja", region: "East", type: "Religious", link: "/festivals/durga-puja", longWeekend: true },
    { date: "Oct 29, 2024", name: "Dhanteras (Diwali Day 1)", region: "Nationwide", type: "Diwali", link: "/festivals/diwali", longWeekend: true },
    { date: "Oct 30, 2024", name: "Naraka Chaturdashi (Diwali Day 2)", region: "Nationwide", type: "Diwali", link: "/festivals/diwali" },
    { date: "Oct 31, 2024", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali", longWeekend: true },
    { date: "Nov 01, 2024", name: "Govardhan Puja (Diwali Day 4)", region: "North & West", type: "Diwali", link: "/festivals/diwali" },
    { date: "Nov 02, 2024", name: "Bhai Dooj (Diwali Day 5)", region: "North & West", type: "Diwali", link: "/festivals/diwali" },
    { date: "Nov 15, 2024", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Dec 01 - Dec 10, 2024", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2024", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },

    // 2025
    { date: "Jan 13, 2025", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri", longWeekend: true },
    { date: "Jan 14, 2025", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 15, 2025", name: "Madai Festival", region: "Central", type: "Cultural", link: "/festivals/madai-festival" },
    { date: "Jan 26, 2025", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 03, 2025", name: "Vasant Panchami", region: "Nationwide", type: "Seasonal", link: "/festivals/vasant-panchami" },
    { date: "Feb 11, 2025", name: "Thaipusam", region: "South", type: "Religious", link: "/festivals/thaipusam" },
    { date: "Feb 22 - Feb 25, 2025", name: "Goa Carnival", region: "West", type: "Cultural", link: "/festivals/goa-carnival" },
    { date: "Feb 26, 2025", name: "Maha Shivaratri", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Mar 01, 2025", name: "Chapchar Kut", region: "Northeast", type: "Cultural", link: "/festivals/chapchar-kut" },
    { date: "Mar 06, 2025", name: "Yaoshang", region: "Northeast", type: "Cultural", link: "/festivals/yaoshang" },
    { date: "Mar 14, 2025", name: "Holi", region: "Nationwide", type: "Holiday", link: "/festivals/holi", longWeekend: true },
    { date: "Mar 30, 2025", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Mar 30, 2025", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr", longWeekend: true },
    { date: "Apr 05, 2025", name: "Mopin", region: "Northeast", type: "Harvest", link: "/festivals/mopin" },
    { date: "Apr 06, 2025", name: "Ram Navami", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Apr 14, 2025", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu", longWeekend: true },
    { date: "Apr 18, 2025", name: "Good Friday", region: "Nationwide", type: "Religious", link: "/festivals/good-friday", longWeekend: true },
    { date: "Apr 21, 2025", name: "Akshaya Tritiya", region: "Nationwide", type: "Religious", link: "/festivals/akshaya-tritiya" },
    { date: "Jun 06, 2025", name: "Eid-al-Adha", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Jun 10, 2025", name: "Hemis Tsechu", region: "North", type: "Cultural", link: "/festivals/hemis-tsechu" },
    { date: "Jun 29, 2025", name: "Rath Yatra", region: "East", type: "Religious", link: "/festivals/rath-yatra" },
    { date: "Jul 28, 2025", name: "Hareli Festival", region: "Central", type: "Harvest", link: "/festivals/hareli-festival" },
    { date: "Jul 28, 2025", name: "Muharram (Ashura)", region: "Nationwide", type: "Religious", link: "/festivals/muharram" },
    { date: "Jul 29, 2025", name: "Nag Panchami", region: "Nationwide", type: "Cultural", link: "/festivals/nag-panchami" },
    { date: "Aug 03, 2025", name: "Teej", region: "North", type: "Monsoon", link: "/festivals/teej" },
    { date: "Aug 09, 2025", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan", longWeekend: true },
    { date: "Aug 15, 2025", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day", longWeekend: true },
    { date: "Aug 17, 2025", name: "Janmashtami", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Aug 22, 2025", name: "Nuakhai", region: "East", type: "Harvest", link: "/festivals/nuakhai" },
    { date: "Aug 27, 2025", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Sep 05, 2025", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Sep 06, 2025", name: "Anant Chaturdashi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Sep 22 - Oct 01, 2025", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri", longWeekend: true },
    { date: "Sep 23 - Dec 06, 2025", name: "Bastar Dussehra", region: "Central", type: "Cultural", link: "/festivals/bastar-dussehra" },
    { date: "Oct 02, 2025", name: "Dussehra", region: "Nationwide", type: "Religious", link: "#", longWeekend: true },
    { date: "Oct 02, 2025", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti", longWeekend: true },
    { date: "Oct 11, 2025", name: "Karva Chauth", region: "North", type: "Cultural", link: "/festivals/karva-chauth" },
    { date: "Oct 19, 2025", name: "Dhanteras (Diwali Day 1)", region: "Nationwide", type: "Diwali", link: "/festivals/diwali", longWeekend: true },
    { date: "Oct 20, 2025", name: "Naraka Chaturdashi (Diwali Day 2)", region: "Nationwide", type: "Diwali", link: "/festivals/diwali", longWeekend: true },
    { date: "Oct 21, 2025", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali", longWeekend: true },
    { date: "Oct 22, 2025", name: "Govardhan Puja (Diwali Day 4)", region: "North & West", type: "Diwali", link: "/festivals/diwali" },
    { date: "Oct 23, 2025", name: "Bhai Dooj (Diwali Day 5)", region: "North & West", type: "Diwali", link: "/festivals/diwali" },
    { date: "Nov 05, 2025", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Nov 11, 2025", name: "Karthigai Deepam", region: "South", type: "Religious", link: "/festivals/karthigai-deepam" },
    { date: "Nov 12, 2025", name: "Wangala", region: "Northeast", type: "Harvest", link: "/festivals/wangala" },
    { date: "Dec 01 - Dec 10, 2025", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2025", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas", longWeekend: true },

    // 2026
    { date: "Jan 13, 2026", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 14, 2026", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 26, 2026", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day", longWeekend: true },
    { date: "Feb 14, 2026", name: "Maha Shivaratri", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Feb 23, 2026", name: "Vasant Panchami", region: "Nationwide", type: "Seasonal", link: "/festivals/vasant-panchami" },
    { date: "Mar 04, 2026", name: "Holi", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 20, 2026", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr", longWeekend: true },
    { date: "Mar 21, 2026", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Mar 28, 2026", name: "Ram Navami", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Apr 03, 2026", name: "Good Friday", region: "Nationwide", type: "Religious", link: "/festivals/good-friday", longWeekend: true },
    { date: "Apr 14, 2026", name: "Vaisakhi / Bihu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "May 26, 2026", name: "Eid-al-Adha", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Jun 18, 2026", name: "Rath Yatra", region: "East", type: "Religious", link: "/festivals/rath-yatra" },
    { date: "Jul 17, 2026", name: "Muharram (Ashura)", region: "Nationwide", type: "Religious", link: "/festivals/muharram" },
    { date: "Aug 07, 2026", name: "Nag Panchami", region: "Nationwide", type: "Cultural", link: "/festivals/nag-panchami" },
    { date: "Aug 15, 2026", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day", longWeekend: true },
    { date: "Aug 26, 2026", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Aug 28, 2026", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan", longWeekend: true },
    { date: "Sep 05, 2026", name: "Janmashtami", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Sep 15, 2026", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Sep 25, 2026", name: "Anant Chaturdashi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Oct 02, 2026", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 12 - Oct 20, 2026", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri", longWeekend: true },
    { date: "Oct 20, 2026", name: "Dussehra", region: "Nationwide", type: "Religious", link: "#", longWeekend: true },
    { date: "Nov 07, 2026", name: "Dhanteras (Diwali Day 1)", region: "Nationwide", type: "Diwali", link: "/festivals/diwali", longWeekend: true },
    { date: "Nov 08, 2026", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali", longWeekend: true },
    { date: "Nov 09, 2026", name: "Govardhan Puja (Diwali Day 4)", region: "North & West", type: "Diwali", link: "/festivals/diwali" },
    { date: "Nov 10, 2026", name: "Bhai Dooj (Diwali Day 5)", region: "North & West", type: "Diwali", link: "/festivals/diwali" },
    { date: "Nov 24, 2026", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Dec 01 - Dec 10, 2026", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2026", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas", longWeekend: true },
    
    // 2027
    { date: "Jan 13, 2027", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 14, 2027", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 26, 2027", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 12, 2027", name: "Vasant Panchami", region: "Nationwide", type: "Seasonal", link: "/festivals/vasant-panchami" },
    { date: "Mar 09, 2027", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr" },
    { date: "Mar 23, 2027", name: "Holi", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Apr 09, 2027", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 14, 2027", name: "Vaisakhi / Bihu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Apr 16, 2027", name: "Good Friday", region: "Nationwide", type: "Religious", link: "/festivals/good-friday" },
    { date: "May 16, 2027", name: "Eid-al-Adha", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Jul 07, 2027", name: "Rath Yatra", region: "East", type: "Religious", link: "/festivals/rath-yatra" },
    { date: "Aug 15, 2027", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 17, 2027", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Aug 18, 2027", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Sep 04, 2027", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Oct 02, 2027", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 02 - Oct 10, 2027", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri" },
    { date: "Oct 28, 2027", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Nov 13, 2027", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Dec 01 - Dec 10, 2027", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2027", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },

    // 2028
    { date: "Jan 13, 2028", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 14, 2028", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 26, 2028", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 25, 2028", name: "Maha Shivaratri", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Feb 27, 2028", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr" },
    { date: "Mar 11, 2028", name: "Holi", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 29, 2028", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 05, 2028", name: "Eid-al-Adha", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Apr 14, 2028", name: "Vaisakhi / Bihu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "May 26, 2028", name: "Muharram (Ashura)", region: "Nationwide", type: "Religious", link: "/festivals/muharram" },
    { date: "Aug 05, 2028", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Aug 06, 2028", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Aug 15, 2028", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 23, 2028", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Sep 21 - Sep 29, 2028", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri" },
    { date: "Oct 02, 2028", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 17, 2028", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Nov 01, 2028", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Dec 01 - Dec 10, 2028", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2028", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },

    // 2029
    { date: "Jan 13, 2029", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 14, 2029", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 26, 2029", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 16, 2029", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr" },
    { date: "Mar 01, 2029", name: "Holi", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 18, 2029", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Mar 25, 2029", name: "Eid-al-Adha", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Apr 14, 2029", name: "Vaisakhi / Bihu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "May 15, 2029", name: "Muharram (Ashura)", region: "Nationwide", type: "Religious", link: "/festivals/muharram" },
    { date: "Aug 15, 2029", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 25, 2029", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Aug 26, 2029", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Sep 12, 2029", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Oct 02, 2029", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 10 - Oct 18, 2029", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri" },
    { date: "Nov 05, 2029", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Nov 20, 2029", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Dec 01 - Dec 10, 2029", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2029", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },

    // 2030
    { date: "Jan 13, 2030", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 14, 2030", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 26, 2030", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 04, 2030", name: "Maha Shivaratri", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Feb 05, 2030", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr" },
    { date: "Mar 19, 2030", name: "Holi", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Apr 07, 2030", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 14, 2030", "name": "Eid-al-Adha", "region": "Nationwide", "type": "Religious", "link": "#" },
    { date: "Apr 14, 2030", "name": "Vaisakhi / Bihu", "region": "North & Northeast", "type": "Harvest", "link": "/festivals/bihu" },
    { date: "May 04, 2030", "name": "Muharram (Ashura)", "region": "Nationwide", "type": "Religious", "link": "/festivals/muharram" },
    { date: "Aug 14, 2030", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Aug 15, 2030", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Sep 01, 2030", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Sep 13, 2030", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Sep 29 - Oct 07, 2030", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri" },
    { date: "Oct 02, 2030", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 25, 2030", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Nov 09, 2030", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Dec 01 - Dec 10, 2030", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2030", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },

    // 2031
    { date: "Jan 13, 2031", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 14, 2031", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 25, 2031", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr" },
    { date: "Jan 26, 2031", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 22, 2031", name: "Maha Shivaratri", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Mar 08, 2031", name: "Holi", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 28, 2031", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 04, 2031", name: "Eid-al-Adha", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Apr 14, 2031", name: "Vaisakhi / Bihu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Apr 23, 2031", name: "Muharram (Ashura)", region: "Nationwide", type: "Religious", link: "/festivals/muharram" },
    { date: "Aug 15, 2031", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Sep 02, 2031", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Sep 20, 2031", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Oct 02, 2031", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 18 - Oct 26, 2031", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri" },
    { date: "Nov 13, 2031", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Nov 28, 2031", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Dec 01 - Dec 10, 2031", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2031", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },

    // 2032
    { date: "Jan 13, 2032", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 14, 2032", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 14, 2032", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr" },
    { date: "Jan 26, 2032", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Mar 23, 2032", name: "Eid-al-Adha", region: "Nationwide", type: "Religious", link: "#" },
    { date: "Mar 26, 2032", name: "Holi", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Apr 12, 2032", name: "Muharram (Ashura)", region: "Nationwide", type: "Religious", link: "/festivals/muharram" },
    { date: "Apr 14, 2032", name: "Vaisakhi / Bihu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 15, 2032", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 22, 2032", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Aug 22, 2032", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Sep 08, 2032", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Oct 02, 2032", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 07 - Oct 15, 2032", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri" },
    { date: "Nov 01, 2032", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Nov 16, 2032", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Dec 01 - Dec 10, 2032", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2032", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },

    // 2033
    { date: "Jan 03, 2033", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr" },
    { date: "Jan 13, 2033", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 14, 2033", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 26, 2033", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Mar 13, 2033", "name": "Eid-al-Adha", "region": "Nationwide", "type": "Religious", "link": "#" },
    { date: "Mar 15, 2033", name: "Holi", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Apr 01, 2033", "name": "Muharram (Ashura)", "region": "Nationwide", "type": "Religious", "link": "/festivals/muharram" },
    { date: "Apr 14, 2033", name: "Vaisakhi / Bihu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 11, 2033", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Aug 15, 2033", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Sep 10, 2033", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Sep 27 - Oct 05, 2033", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri" },
    { date: "Sep 28, 2033", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Oct 02, 2033", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 21, 2033", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Dec 01 - Dec 10, 2033", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 24, 2033", "name": "Eid-al-Fitr", "region": "Nationwide", "type": "Religious", "link": "/festivals/eid-al-fitr" },
    { date: "Dec 25, 2033", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },

    // 2034
    { date: "Jan 13, 2034", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 14, 2034", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 26, 2034", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Mar 02, 2034", "name": "Eid-al-Adha", "region": "Nationwide", "type": "Religious", "link": "#" },
    { date: "Mar 04, 2034", name: "Holi", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 21, 2034", "name": "Muharram (Ashura)", "region": "Nationwide", "type": "Religious", "link": "/festivals/muharram" },
    { date: "Apr 14, 2034", name: "Vaisakhi / Bihu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 15, 2034", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 31, 2034", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Aug 31, 2034", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Sep 17, 2034", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Oct 02, 2034", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 16 - Oct 24, 2034", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri" },
    { date: "Nov 10, 2034", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Dec 01 - Dec 10, 2034", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 13, 2034", "name": "Eid-al-Fitr", "region": "Nationwide", "type": "Religious", "link": "/festivals/eid-al-fitr" },
    { date: "Dec 25, 2034", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" }
];
