
export const allFestivals = [
    { name: "Diwali", region: "Nationwide", description: "The festival of lights, symbolizing the victory of light over darkness and good over evil.", link: "/festivals/diwali", image: "https://i.postimg.cc/SjF8HhM1/Diwali2.jpg", hint: "diwali celebration" },
    { name: "Holi", region: "Nationwide", description: "The vibrant festival of colors, celebrating the arrival of spring, love, and the triumph of good.", link: "/festivals/holi", image: "https://i.postimg.cc/0276MjRN/Holi.jpg", hint: "holi celebration" },
    { name: "Eid-al-Fitr", region: "Nationwide", description: "Marking the end of Ramadan, this festival is a joyous celebration of feasting, prayer, and charity.", link: "/festivals/eid-al-fitr", image: "https://i.postimg.cc/1tMsX8bp/eid-al-fitr.avif", hint: "eid family" },
    { name: "Navratri", region: "Nationwide", description: "A nine-night festival dedicated to worshipping the nine forms of the goddess Durga, famous for its energetic Garba dances.", link: "/festivals/navratri", image: "https://i.postimg.cc/J4JFtVYT/navratri1.jpg", hint: "garba dance" },
    { name: "Durga Puja", region: "East", description: "A grand ten-day festival in Bengal celebrating the goddess Durga's victory over the demon Mahishasur.", link: "/festivals/durga-puja", image: "https://i.postimg.cc/nL3Jwd9d/East-India-festivals.webp", hint: "durga idol" },
    { name: "Ganesh Chaturthi", region: "West & South", description: "A spectacular festival celebrating the birth of Lord Ganesha, the god of new beginnings and wisdom.", link: "/festivals/ganesh-chaturthi", image: "https://i.postimg.cc/SNGxJ8VJ/ganesh-chaturthi-festival.jpg", hint: "ganesha idol" },
    { name: "Christmas", region: "Nationwide", description: "Celebrating the birth of Jesus Christ, marked by carols, feasts, and the spirit of giving.", link: "/festivals/christmas", image: "https://i.postimg.cc/rpDTKRn2/Christmas.webp", hint: "christmas decor" },
    { name: "Pongal", region: "South", description: "A four-day harvest festival in Tamil Nadu to thank the Sun God, Surya, for a bountiful harvest.", link: "/festivals/pongal", image: "https://i.postimg.cc/bvmpScwr/pongal.jpg", hint: "pongal dish" },
    { name: "Onam", region: "South", description: "Kerala's most important harvest festival, celebrating the homecoming of the mythical King Mahabali.", link: "/festivals/onam", image: "https://i.postimg.cc/0564g0S7/nandu-menon-h-GHldb-Cg-YDA-unsplash.jpg", hint: "onam feast" },
    { name: "Bihu", region: "Northeast", description: "A set of three Assamese festivals celebrating different phases of the farming calendar with folk dance and music.", link: "/festivals/bihu", image: "https://i.postimg.cc/k5GJKp5Z/vaisakhi.webp", hint: "bihu dance" },
    { name: "Makar Sankranti", region: "Nationwide", description: "A festival marking the sun's transit into Capricorn, celebrated with kite flying, bonfires, and feasts.", link: "/festivals/makar-sankranti", image: "https://i.postimg.cc/gJrdvSxD/makar-sankranti.jpg", hint: "kites festival" },
    { name: "Guru Nanak Jayanti", region: "Nationwide", description: "Celebrating the birth of the first Sikh Guru, Guru Nanak Dev Ji, with prayers and hymns.", link: "/festivals/guru-nanak-jayanti", image: "https://i.postimg.cc/029q7BWf/guru-nanak-jayanti.webp", hint: "sikh prayer" },
    { name: "Raksha Bandhan", region: "Nationwide", description: "A festival that celebrates the cherished bond between brothers and sisters, marked by the tying of a sacred thread.", link: "/festivals/raksha-bandhan", image: "https://i.postimg.cc/9MXxXQhY/Raksha-Bandhan.jpg", hint: "rakhi thread" },
    { name: "Chhath Puja", region: "North & East", description: "An ancient Hindu festival dedicated to the Sun God, Surya, thanking him for sustaining life on earth.", link: "/festivals/chhath-puja", image: "https://i.postimg.cc/KYmDZCCg/chath-puja-festival1.webp", hint: "chhath puja" },
    { name: "Rath Yatra", region: "East", description: "The spectacular chariot festival of Lord Jagannath celebrated in Puri and other cities.", link: "/festivals/rath-yatra", image: "https://i.postimg.cc/kXC7f44W/rath-yatra.jpg", hint: "chariot festival" },
    { name: "Gudi Padwa", region: "West", description: "The Maharashtrian New Year, celebrated with the hoisting of a 'Gudi' and festive foods.", link: "/festivals/gudi-padwa", image: "https://i.postimg.cc/DwjFvPcc/gudi-padwa.webp", hint: "gudi flag" },
    { name: "Lohri", region: "North", description: "A popular Punjabi folk festival, celebrating the winter solstice and the harvest of rabi crops.", link: "/festivals/lohri", image: "https://i.postimg.cc/MGgSRZNM/lohri-1.webp", hint: "lohri bonfire" },
    { name: "Vasant Panchami", region: "Nationwide", description: "A festival that marks the preparation for the arrival of spring, dedicated to the goddess Saraswati.", link: "/festivals/vasant-panchami", image: "https://i.postimg.cc/15KsTQn2/Vasant-Panchami.webp", hint: "saraswati idol" },
    { name: "Muharram", region: "Nationwide", description: "A solemn period of remembrance and mourning for Shia Muslims, commemorating the martyrdom of Imam Hussein.", link: "/festivals/muharram", image: "https://i.postimg.cc/j5JRknP4/Muharram.webp", hint: "muharram procession" },
    { name: "Akshaya Tritiya", region: "Nationwide", description: "An auspicious day of eternal prosperity, believed to bring good fortune and success.", link: "/festivals/akshaya-tritiya", image: "https://i.postimg.cc/Rh92QWRF/dhanteras1.webp", hint: "gold coins" },
    { name: "Nag Panchami", region: "Nationwide", description: "A traditional day of serpent worship, observed by offering milk and prayers to snake deities.", link: "/festivals/nag-panchami", image: "https://i.postimg.cc/SRFm0QGF/nag-panchami.webp", hint: "snake worship" },
    { name: "Hornbill Festival", region: "Northeast", description: "A vibrant festival in Nagaland showcasing the rich culture and traditions of the Naga tribes.", link: "/festivals/hornbill-festival", image: "https://i.postimg.cc/6pL9wGsd/Hornbill-Festival.webp", hint: "naga festival" },
    { name: "Thaipusam", region: "South", description: "A powerful Tamil festival of faith, endurance, and penance dedicated to Lord Murugan.", link: "/festivals/thaipusam", image: "https://i.postimg.cc/4y7fTLZd/thaipusam.webp", hint: "kavadi" },
    { name: "Hemis Tsechu", region: "North", description: "A colorful Buddhist festival in Ladakh with masked dances celebrating the birth of Guru Padmasambhava.", link: "/festivals/hemis-tsechu", image: "https://i.postimg.cc/mDBXxRCR/losar-2.jpg", hint: "ladakh festival" },
    { name: "Goa Carnival", region: "West", description: "A vibrant and energetic carnival in Goa with Portuguese roots, featuring parades, music, and dance.", link: "/festivals/goa-carnival", image: "https://i.postimg.cc/4xZYzGsQ/Goa-Carnival.jpg", hint: "goa carnival" },
    { name: "Republic Day", region: "Nationwide", description: "Celebrating the adoption of the Indian Constitution with a grand parade in the capital.", link: "/festivals/republic-day", image: "https://i.postimg.cc/W4kyBGYz/independence-day.avif", hint: "indian army parade" },
    { name: "Independence Day", region: "Nationwide", description: "Commemorating India's freedom from British rule, marked by flag-hoisting ceremonies.", link: "/festivals/independence-day", image: "https://i.postimg.cc/W4kyBGYz/independence-day.avif", hint: "indian flag" },
    { name: "Gandhi Jayanti", region: "Nationwide", description: "Marking the birth anniversary of Mahatma Gandhi, the 'Father of the Nation'.", link: "/festivals/gandhi-jayanti", image: "https://i.postimg.cc/bJ1Ktx1W/gandhi-jayanti.webp", hint: "mahatma gandhi" },
    { name: "Good Friday", region: "Nationwide", description: "A Christian holiday commemorating the crucifixion of Jesus Christ.", link: "/festivals/good-friday", image: "https://i.postimg.cc/ncKMYdWy/christmas-2.jpg", hint: "church cross" },
    { name: "Bastar Dussehra", region: "Central", description: "A unique 75-day long Dussehra celebration in Chhattisgarh's Bastar region, focused on nature and local deities.", link: "/festivals/bastar-dussehra", image: "https://i.postimg.cc/wMVZW9fk/dussehra.jpg", hint: "dussehra celebration" },
    { name: "Hareli Festival", region: "Central", description: "A harvest festival in Chhattisgarh marking the beginning of the Shravan month with worship of farm equipment and cattle.", link: "/festivals/hareli-festival", image: "https://i.postimg.cc/MZCMpRL4/hareli.png", hint: "tribal festival" },
    { name: "Madai Festival", region: "Central", description: "A prominent tribal festival of the Gond tribe in Chhattisgarh, involving rituals and folk dances.", link: "/festivals/madai-festival", image: "https://i.postimg.cc/sfQGzKT7/madai-festival.jpg", hint: "tribal fair" },
    { name: "Teej", region: "North", description: "A monsoon festival celebrating the union of Shiva and Parvati, observed by women with fasting and prayers.", link: "/festivals/teej", image: "https://i.postimg.cc/kGQ9w7QS/north-india-festivals.webp", hint: "teej swings" },
    { name: "Karva Chauth", region: "North", description: "A traditional Hindu festival where married women fast for the longevity and well-being of their husbands.", link: "/festivals/karva-chauth", image: "https://i.postimg.cc/k500G1RW/karva-chauth.webp", hint: "karva chauth puja" },
    { name: "Ugadi", region: "South", description: "The New Year's Day for the people of Andhra Pradesh, Telangana, and Karnataka.", link: "/festivals/ugadi", image: "https://i.postimg.cc/ZnGTY8KL/ugadi.jpg", hint: "ugadi pachadi" },
    { name: "Vishu", region: "South", description: "The astronomical new year festival celebrated in Kerala, marking the first day of Medam.", link: "/festivals/vishu", image: "https://i.postimg.cc/7PdPNkMT/vishu-celebration.png", hint: "vishu kani" },
    { name: "Karthigai Deepam", region: "South", description: "A festival of lights celebrated by Tamil Hindus, where homes are decorated with oil lamps.", link: "/festivals/karthigai-deepam", image: "https://i.postimg.cc/Y26HGH30/karthigai-deepam.jpg", hint: "diya lamps" },
    { name: "Yaoshang", region: "Northeast", description: "Manipur's biggest festival, celebrated for five days, combining Hindu and indigenous traditions.", link: "/festivals/yaoshang", image: "https://i.postimg.cc/LXs4x4bj/yaoshang.webp", hint: "manipur festival" },
    { name: "Chapchar Kut", region: "Northeast", description: "A spring festival of Mizoram celebrated after the completion of their most arduous task of jhum cultivation.", link: "/festivals/chapchar-kut", image: "https://i.postimg.cc/G2NRzFY1/chapchar-kut1.jpg", hint: "mizo dance" },
    { name: "Mopin", region: "Northeast", description: "A vibrant harvest festival of the Galo tribe in Arunachal Pradesh to drive away evil spirits.", link: "/festivals/mopin", image: "https://i.postimg.cc/Dzv7zyFR/mopin-festival.jpg", hint: "galo tribe" },
    { name: "Wangala", region: "Northeast", description: "A harvest festival of the Garo tribe in Meghalaya, also known as the 100 Drums festival.", link: "/festivals/wangala", image: "https://i.postimg.cc/50vMmdWP/Wangala.webp", hint: "garo dance" },
    { name: "Nuakhai", region: "East", description: "An agricultural festival in Odisha to welcome the new rice of the season.", link: "/festivals/nuakhai", image: "https://i.postimg.cc/zGMM2tj4/nuakhai.avif", hint: "odisha festival" },
    { name: "Maha Shivaratri", region: "Nationwide", description: "A major festival dedicated to the worship of Lord Shiva, the god of destruction.", link: "/festivals/maha-shivaratri", image: "https://i.postimg.cc/52NbWR80/mahashivratri.jpg", hint: "shiva statue" },
    { name: "Ram Navami", region: "Nationwide", description: "Celebrating the birth of Lord Rama, the seventh avatar of Vishnu.", link: "/festivals/ram-navami", image: "https://i.postimg.cc/Vvqmzy7S/ram-navami.webp", hint: "lord rama" },
    { name: "Anant Chaturdashi", region: "West & South", description: "The final day of the Ganesh Chaturthi festival, marking the immersion of Ganesha idols.", link: "/festivals/anant-chaturdashi", image: "https://i.postimg.cc/RVSjWnhp/anant-chaturdashi.jpg", hint: "ganesh visarjan" },
    { name: "Eid-al-Adha", region: "Nationwide", description: "The 'Festival of Sacrifice', one of the two main Islamic holidays.", link: "/festivals/eid-al-adha", image: "https://i.postimg.cc/KYWZNDkY/eid-al-adha.webp", hint: "eid prayer" },
    { name: "Janmashtami", region: "Nationwide", description: "Celebrating the birth of Lord Krishna, the eighth avatar of Vishnu.", link: "/festivals/janmashtami", image: "https://i.postimg.cc/02VhD2Jk/janmashtami.jpg", hint: "krishna idol" },
    { name: "Ashadhi Ekadashi", region: "West", description: "The great pilgrimage of faith to Pandharpur, honoring Lord Vithoba.", link: "/festivals/ashadhi-ekadashi", image: "https://i.postimg.cc/WpCxTcdd/ashadhi-ekadashi.jpg", hint: "palanquin procession" },
    { name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", description: "Celebrating the birth of the legendary Maratha warrior king.", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti", image: "https://i.postimg.cc/K8yV37rF/chhatrapati-shivaji-maharaj-jayanti.webp", hint: "maratha king" },
    { name: "Hanuman Jayanti", region: "Nationwide", description: "Celebrating the birth of Lord Hanuman, the embodiment of devotion and strength.", link: "/festivals/hanuman-jayanti", image: "https://i.postimg.cc/9fCpCJPR/hanuman-jayanti3.jpg", hint: "hanuman idol" },
    { name: "Hartalika Teej", region: "North", description: "A rigorous fast observed by women for marital bliss, honoring Goddess Parvati.", link: "/festivals/hartalika-teej", image: "https://i.postimg.cc/509nqn6d/Hartalika-Teej.webp", hint: "parvati shiva" },
    { name: "Holika Dahan", region: "Nationwide", description: "The sacred bonfire ritual on the eve of Holi, symbolizing the victory of good over evil.", link: "/festivals/holika-dahan", image: "https://i.postimg.cc/qBzWPvvf/holika-dahan.webp", hint: "bonfire festival" },
    { name: "Kojagiri Purnima", region: "West & East", description: "The autumn harvest moon festival, celebrated by worshipping Goddess Lakshmi.", link: "/festivals/kojagiri-purnima", image: "https://i.postimg.cc/L8BWtqNP/kojagiri-purnima.webp", hint: "full moon" },
    { name: "Mando Festival", region: "West", description: "A Goan festival celebrating its unique musical heritage of lyrical dance-songs.", link: "/festivals/mando-festival", image: "https://i.postimg.cc/mktjKkYm/Mando.jpg", hint: "goan folk dance" },
    { name: "Narali Purnima", region: "West", description: "The coconut festival of coastal Maharashtra, where offerings are made to the sea god.", link: "/festivals/narali-purnima", image: "https://i.postimg.cc/4xz5DrcR/Narali-purnima.avif", hint: "coconut offering sea" },
    { name: "Parsi New Year (Pateti & Navroz)", region: "Nationwide", description: "The joyous New Year celebration of the Parsi community, marking renewal and rejuvenation.", link: "/festivals/parsi-new-year", image: "https://i.postimg.cc/bwD0xd8T/navroz1.webp", hint: "parsi celebration" },
    { name: "Shigmo Festival", region: "West", description: "Goa's vibrant spring festival, similar to Holi, with grand parades and folk dances.", link: "/festivals/shigmo-festival", image: "https://i.postimg.cc/T24CgjxF/Shigmo2.png", hint: "goa parade" },
    { name: "Vat Purnima", region: "West", description: "A celebration of marital fidelity, where women pray for their husband's long life under a banyan tree.", link: "/festivals/vat-purnima", image: "https://i.postimg.cc/02SFNXSc/vat-purnima.webp", hint: "banyan tree worship" },
    { name: "Tulsi Vivah", region: "Nationwide", description: "The ceremonial wedding of the holy basil plant (Tulsi) to Lord Vishnu.", link: "/festivals/tulsi-vivah", image: "https://i.postimg.cc/dVLB1Lgv/tulsi-vivah.jpg", hint: "sacred marriage" },
];

export const allEvents = [
    // 2025
    { date: "Jan 13, 2025", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri", longWeekend: true },
    { date: "Jan 14, 2025", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti", longWeekend: true },
    { date: "Jan 15, 2025", name: "Madai Festival", region: "Central", type: "Cultural", link: "/festivals/madai-festival" },
    { date: "Jan 26, 2025", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 03, 2025", name: "Vasant Panchami", region: "Nationwide", type: "Seasonal", link: "/festivals/vasant-panchami" },
    { date: "Feb 11, 2025", name: "Thaipusam", region: "South", type: "Religious", link: "/festivals/thaipusam" },
    { date: "Feb 19, 2025", name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", type: "Holiday", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti" },
    { date: "Feb 22 - Feb 25, 2025", name: "Goa Carnival", region: "West", type: "Cultural", link: "/festivals/goa-carnival" },
    { date: "Feb 26, 2025", name: "Maha Shivaratri", region: "Nationwide", type: "Religious", link: "/festivals/maha-shivaratri" },
    { date: "Mar 01, 2025", name: "Chapchar Kut", region: "Northeast", type: "Cultural", link: "/festivals/chapchar-kut" },
    { date: "Mar 06, 2025", name: "Yaoshang", region: "Northeast", type: "Cultural", link: "/festivals/yaoshang" },
    { date: "Mar 13, 2025", name: "Holika Dahan (Holi Day 1)", region: "Nationwide", type: "Religious", link: "/festivals/holika-dahan" },
    { date: "Mar 14, 2025", name: "Holi (Festival of Colors)", region: "Nationwide", type: "Holiday", link: "/festivals/holi", longWeekend: true },
    { date: "Mar 15, 2025", name: "Shigmo Festival", region: "West", type: "Cultural", link: "/festivals/shigmo-festival" },
    { date: "Mar 30, 2025", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Mar 30, 2025", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr", longWeekend: true },
    { date: "Apr 05, 2025", name: "Mopin", region: "Northeast", type: "Harvest", link: "/festivals/mopin" },
    { date: "Apr 06, 2025", name: "Ram Navami", region: "Nationwide", type: "Religious", link: "/festivals/ram-navami" },
    { date: "Apr 14, 2025", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu", longWeekend: true },
    { date: "Apr 16, 2025", name: "Hanuman Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/hanuman-jayanti" },
    { date: "Apr 18, 2025", name: "Good Friday", region: "Nationwide", type: "Religious", link: "/festivals/good-friday", longWeekend: true },
    { date: "Apr 21, 2025", name: "Akshaya Tritiya", region: "Nationwide", type: "Religious", link: "/festivals/akshaya-tritiya", longWeekend: true },
    { date: "Jun 06, 2025", name: "Eid-al-Adha", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-adha", longWeekend: true },
    { date: "Jun 10, 2025", name: "Hemis Tsechu", region: "North", type: "Cultural", link: "/festivals/hemis-tsechu" },
    { date: "Jun 21, 2025", name: "Vat Purnima", region: "West", type: "Cultural", link: "/festivals/vat-purnima" },
    { date: "Jun 29, 2025", name: "Rath Yatra", region: "East", type: "Religious", link: "/festivals/rath-yatra" },
    { date: "Jul 06, 2025", name: "Ashadhi Ekadashi", region: "West", type: "Religious", link: "/festivals/ashadhi-ekadashi" },
    { date: "Jul 28, 2025", name: "Hareli Festival", region: "Central", type: "Harvest", link: "/festivals/hareli-festival" },
    { date: "Jul 28, 2025", name: "Muharram (Ashura)", region: "Nationwide", type: "Religious", link: "/festivals/muharram" },
    { date: "Jul 29, 2025", name: "Nag Panchami", region: "Nationwide", type: "Cultural", link: "/festivals/nag-panchami" },
    { date: "Aug 03, 2025", name: "Teej", region: "North", type: "Monsoon", link: "/festivals/teej" },
    { date: "Aug 09, 2025", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Aug 09, 2025", name: "Narali Purnima", region: "West", type: "Cultural", link: "/festivals/narali-purnima" },
    { date: "Aug 15, 2025", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day", longWeekend: true },
    { date: "Aug 16, 2025", name: "Parsi New Year (Pateti & Navroz)", region: "Nationwide", type: "New Year", link: "/festivals/parsi-new-year" },
    { date: "Aug 17, 2025", name: "Janmashtami", region: "Nationwide", type: "Religious", link: "/festivals/janmashtami" },
    { date: "Aug 22, 2025", name: "Nuakhai", region: "East", type: "Harvest", link: "/festivals/nuakhai", longWeekend: true },
    { date: "Aug 27, 2025", name: "Ganesh Chaturthi", region: "West & South", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Aug 27, 2025", name: "Hartalika Teej", region: "North", type: "Cultural", link: "/festivals/hartalika-teej" },
    { date: "Sep 05, 2025", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam", longWeekend: true },
    { date: "Sep 06, 2025", name: "Anant Chaturdashi", region: "West & South", type: "Religious", link: "/festivals/anant-chaturdashi" },
    { date: "Sep 22 - Oct 01, 2025", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri", longWeekend: true },
    { date: "Sep 23 - Dec 06, 2025", name: "Bastar Dussehra", region: "Central", type: "Cultural", link: "/festivals/bastar-dussehra" },
    { date: "Oct 02, 2025", name: "Dussehra", region: "Nationwide", type: "Religious", link: "/festivals/dussehra", longWeekend: true },
    { date: "Oct 02, 2025", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti", longWeekend: true },
    { date: "Oct 05, 2025", name: "Kojagiri Purnima", region: "West & East", type: "Religious", link: "/festivals/kojagiri-purnima" },
    { date: "Oct 11, 2025", name: "Karva Chauth", region: "North", type: "Cultural", link: "/festivals/karva-chauth" },
    { date: "Oct 19, 2025", name: "Dhanteras (Diwali Day 1)", region: "Nationwide", type: "Diwali", link: "/festivals/diwali" },
    { date: "Oct 20, 2025", name: "Naraka Chaturdashi (Diwali Day 2)", region: "Nationwide", type: "Diwali", link: "/festivals/diwali" },
    { date: "Oct 21, 2025", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali", longWeekend: true },
    { date: "Oct 22, 2025", name: "Govardhan Puja / Padwa (Diwali Day 4)", region: "North & West", type: "Diwali", link: "/festivals/diwali" },
    { date: "Oct 23, 2025", name: "Bhai Dooj (Diwali Day 5)", region: "North & West", type: "Diwali", link: "/festivals/diwali" },
    { date: "Nov 01, 2025", name: "Tulsi Vivah", region: "Nationwide", type: "Religious", link: "/festivals/tulsi-vivah" },
    { date: "Nov 05, 2025", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Nov 11, 2025", name: "Karthigai Deepam", region: "South", type: "Religious", link: "/festivals/karthigai-deepam" },
    { date: "Nov 12, 2025", name: "Wangala", region: "Northeast", type: "Harvest", link: "/festivals/wangala" },
    { date: "Dec 01 - Dec 10, 2025", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2025", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas", longWeekend: true },

    // 2026
    { date: "Jan 13, 2026", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 14, 2026", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 23, 2026", name: "Vasant Panchami", region: "Nationwide", type: "Seasonal", link: "/festivals/vasant-panchami", longWeekend: true },
    { date: "Jan 26, 2026", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day", longWeekend: true },
    { date: "Feb 01, 2026", name: "Thaipusam", region: "South", type: "Religious", link: "/festivals/thaipusam" },
    { date: "Feb 13 - Feb 16, 2026", name: "Goa Carnival", region: "West", type: "Cultural", link: "/festivals/goa-carnival", longWeekend: true },
    { date: "Feb 14, 2026", name: "Maha Shivaratri", region: "Nationwide", type: "Religious", link: "/festivals/maha-shivaratri" },
    { date: "Feb 19, 2026", name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", type: "Holiday", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti" },
    { date: "Mar 04, 2026", name: "Holika Dahan (Holi Day 1)", region: "Nationwide", type: "Religious", link: "/festivals/holika-dahan" },
    { date: "Mar 05, 2026", name: "Holi (Festival of Colors)", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 06, 2026", name: "Shigmo Festival", region: "West", type: "Cultural", link: "/festivals/shigmo-festival" },
    { date: "Mar 20, 2026", name: "Eid-al-Fitr", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-fitr", longWeekend: true },
    { date: "Mar 21, 2026", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Mar 26, 2026", name: "Ram Navami", region: "Nationwide", type: "Religious", link: "/festivals/ram-navami" },
    { date: "Apr 03, 2026", name: "Good Friday", region: "Nationwide", type: "Religious", link: "/festivals/good-friday", longWeekend: true },
    { date: "Apr 05, 2026", name: "Hanuman Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/hanuman-jayanti" },
    { date: "Apr 10, 2026", name: "Akshaya Tritiya", region: "Nationwide", type: "Religious", link: "/festivals/akshaya-tritiya", longWeekend: true },
    { date: "Apr 14, 2026", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "May 27, 2026", name: "Vat Purnima", region: "West", type: "Cultural", link: "/festivals/vat-purnima" },
    { date: "May 27, 2026", name: "Eid-al-Adha", region: "Nationwide", type: "Religious", link: "/festivals/eid-al-adha" },
    { date: "Jun 17, 2026", name: "Muharram (Ashura)", region: "Nationwide", type: "Religious", link: "/festivals/muharram" },
    { date: "Jun 18, 2026", name: "Rath Yatra", region: "East", type: "Religious", link: "/festivals/rath-yatra" },
    { date: "Jun 25, 2026", name: "Ashadhi Ekadashi", region: "West", type: "Religious", link: "/festivals/ashadhi-ekadashi" },
    { date: "Jul 18, 2026", name: "Hareli Festival", region: "Central", type: "Harvest", link: "/festivals/hareli-festival" },
    { date: "Jul 18, 2026", name: "Nag Panchami", region: "Nationwide", type: "Cultural", link: "/festivals/nag-panchami" },
    { date: "Aug 07, 2026", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan", longWeekend: true },
    { date: "Aug 07, 2026", name: "Narali Purnima", region: "West", type: "Cultural", link: "/festivals/narali-purnima" },
    { date: "Aug 15, 2026", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 16, 2026", name: "Hartalika Teej", region: "North", type: "Cultural", link: "/festivals/hartalika-teej" },
    { date: "Aug 16, 2026", name: "Parsi New Year (Pateti & Navroz)", region: "Nationwide", type: "New Year", link: "/festivals/parsi-new-year" },
    { date: "Aug 26, 2026", name: "Onam", region: "South", type: "Harvest", link: "/festivals/onam" },
    { date: "Sep 15, 2026", name: "Ganesh Chaturthi", region: "West", type: "Religious", link: "/festivals/ganesh-chaturthi" },
    { date: "Sep 25, 2026", name: "Kojagiri Purnima", region: "West & East", type: "Religious", link: "/festivals/kojagiri-purnima" },
    { date: "Oct 02, 2026", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti", longWeekend: true },
    { date: "Oct 12 - Oct 20, 2026", name: "Navratri", region: "Nationwide", type: "Religious", link: "/festivals/navratri", longWeekend: true },
    { date: "Oct 16 - Oct 20, 2026", name: "Durga Puja", region: "East", type: "Religious", link: "/festivals/durga-puja" },
    { date: "Oct 21, 2026", name: "Dussehra", region: "Nationwide", type: "Religious", link: "/festivals/dussehra" },
    { date: "Oct 31, 2026", name: "Karva Chauth", region: "North", type: "Cultural", link: "/festivals/karva-chauth" },
    { date: "Nov 08, 2026", name: "Diwali (Lakshmi Puja)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Nov 21, 2026", name: "Tulsi Vivah", region: "Nationwide", type: "Religious", link: "/festivals/tulsi-vivah" },
    { date: "Nov 24, 2026", name: "Guru Nanak Jayanti", region: "Nationwide", type: "Religious", link: "/festivals/guru-nanak-jayanti" },
    { date: "Dec 01 - Dec 10, 2026", name: "Hornbill Festival", region: "Northeast", type: "Cultural", link: "/festivals/hornbill-festival" },
    { date: "Dec 25, 2026", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas", longWeekend: true },
    { date: "Jan 14, 2027", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 13, 2027", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 26, 2027", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 19, 2027", name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", type: "Holiday", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti" },
    { date: "Mar 25, 2027", name: "Holi (Festival of Colors)", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 10, 2027", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 14, 2027", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 15, 2027", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 26, 2027", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Oct 02, 2027", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Nov 09, 2027", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Dec 25, 2027", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },
    { date: "Jan 14, 2028", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 13, 2028", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 26, 2028", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 19, 2028", name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", type: "Holiday", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti" },
    { date: "Mar 13, 2028", name: "Holi (Festival of Colors)", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 28, 2028", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 14, 2028", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 15, 2028", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 15, 2028", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Oct 02, 2028", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 28, 2028", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Dec 25, 2028", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },
    { date: "Jan 14, 2029", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 13, 2029", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 26, 2029", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 19, 2029", name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", type: "Holiday", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti" },
    { date: "Mar 02, 2029", name: "Holi (Festival of Colors)", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 17, 2029", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 14, 2029", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 15, 2029", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 04, 2029", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Oct 02, 2029", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Nov 16, 2029", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Dec 25, 2029", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },
    { date: "Jan 14, 2030", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 13, 2030", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 26, 2030", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 19, 2030", name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", type: "Holiday", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti" },
    { date: "Mar 20, 2030", name: "Holi (Festival of Colors)", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Apr 05, 2030", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 14, 2030", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 15, 2030", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 23, 2030", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Oct 02, 2030", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Nov 05, 2030", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Dec 25, 2030", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },
    { date: "Jan 14, 2031", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 13, 2031", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 26, 2031", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 19, 2031", name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", type: "Holiday", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti" },
    { date: "Mar 10, 2031", name: "Holi (Festival of Colors)", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 26, 2031", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 14, 2031", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 13, 2031", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Aug 15, 2031", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Oct 02, 2031", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 26, 2031", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Dec 25, 2031", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },
    { date: "Jan 14, 2032", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 13, 2032", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 26, 2032", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 19, 2032", name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", type: "Holiday", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti" },
    { date: "Feb 27, 2032", name: "Holi (Festival of Colors)", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 14, 2032", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 14, 2032", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 15, 2032", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 20, 2032", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Oct 02, 2032", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Nov 13, 2032", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Dec 25, 2032", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },
    { date: "Jan 14, 2033", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 13, 2033", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 26, 2033", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 19, 2033", name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", type: "Holiday", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti" },
    { date: "Mar 18, 2033", name: "Holi (Festival of Colors)", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Apr 02, 2033", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 14, 2033", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 10, 2033", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Aug 15, 2033", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Oct 02, 2033", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Nov 02, 2033", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Dec 25, 2033", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },
    { date: "Jan 14, 2034", name: "Makar Sankranti / Pongal", region: "Nationwide", type: "Harvest", link: "/festivals/makar-sankranti" },
    { date: "Jan 13, 2034", name: "Lohri", region: "North", type: "Harvest", link: "/festivals/lohri" },
    { date: "Jan 26, 2034", name: "Republic Day", region: "Nationwide", type: "Holiday", link: "/festivals/republic-day" },
    { date: "Feb 19, 2034", name: "Chhatrapati Shivaji Maharaj Jayanti", region: "West", type: "Holiday", link: "/festivals/chhatrapati-shivaji-maharaj-jayanti" },
    { date: "Mar 07, 2034", name: "Holi (Festival of Colors)", region: "Nationwide", type: "Holiday", link: "/festivals/holi" },
    { date: "Mar 23, 2034", name: "Gudi Padwa / Ugadi", region: "West & South", type: "New Year", link: "/festivals/gudi-padwa" },
    { date: "Apr 14, 2034", name: "Vaisakhi / Bihu / Vishu", region: "North & Northeast", type: "Harvest", link: "/festivals/bihu" },
    { date: "Aug 15, 2034", name: "Independence Day", region: "Nationwide", type: "Holiday", link: "/festivals/independence-day" },
    { date: "Aug 29, 2034", name: "Raksha Bandhan", region: "Nationwide", type: "Cultural", link: "/festivals/raksha-bandhan" },
    { date: "Oct 02, 2034", name: "Gandhi Jayanti", region: "Nationwide", type: "Holiday", link: "/festivals/gandhi-jayanti" },
    { date: "Oct 22, 2034", name: "Diwali (Lakshmi Puja) (Day 3)", region: "Nationwide", type: "Holiday", link: "/festivals/diwali" },
    { date: "Dec 25, 2034", name: "Christmas", region: "Nationwide", type: "Religious", link: "/festivals/christmas" },
];

export const internationalFestivals = [
    { name: "Chinese New Year", region: "International", description: "The vibrant 15-day celebration of the lunar new year, filled with dragon dances, red lanterns, and feasting.", link: "/festivals/chinese-new-year", image: "https://i.postimg.cc/Pq9v7Zt2/chinese-new-year.jpg", hint: "dragon dance" },
    { name: "Cherry Blossom Festival (Hanami)", region: "International", description: "Japan's serene festival celebrating the transient beauty of cherry blossoms with picnics under the sakura trees.", link: "/festivals/cherry-blossom-festival", image: "https://i.postimg.cc/T3sT8JgC/cherry-blossom-festival-japan.jpg", hint: "cherry blossoms" },
    { name: "Dia de los Muertos (Day of the Dead)", region: "International", description: "A colorful Mexican holiday honoring deceased loved ones with altars, sugar skulls, and marigolds.", link: "/festivals/dia-de-los-muertos", image: "https://i.postimg.cc/tJnzyzKz/dia-de-los-muertos.jpg", hint: "day of the dead" },
    { name: "Songkran (Thai Water Festival)", region: "International", description: "Thailand's wild and joyous New Year celebration, famous for its nationwide water fights symbolizing purification.", link: "/festivals/songkran", image: "https://i.postimg.cc/5Nc7pGdk/songkran-water-festival.jpg", hint: "water festival" },
    { name: "Boun Ok Phansa (Festival of Lights)", region: "International", description: "A beautiful Laotian festival marking the end of Buddhist Lent by releasing illuminated boats on rivers.", link: "/festivals/boun-ok-phansa", image: "https://i.postimg.cc/HxbY5g1b/boun-ok-phansa.jpg", hint: "laos light festival" },
    { name: "Harbin Ice and Snow Festival", region: "International", description: "A breathtaking winter festival in China featuring gigantic, illuminated ice and snow sculptures.", link: "/festivals/harbin-ice-festival", image: "https://i.postimg.cc/d1hJc6Xv/harbin-ice-festival.jpg", hint: "ice sculptures" },
];

    